server:
  port: 8181



spring:
  data:
    cassandra:
      #username: cassandra
      #password: cassandra
      keyspace: "vafeature"
      contact-points: "localhost"
      port: 9042
      #schemaAction: NONE










