server:
  port: 8181

<!--Cassandra Config for datasource-->
spring:
  data:
  cassandra:
  keyspaceName: quangkeyspace
  contactPoints: localhost
  port: 9042
  schemaAction: CREATE_IF_NOT_EXISTS
  entity-base-package:  com.RogersClient.RogersClientCrudOperation.model
